public class CWH_ch_02_pr_01 {
    public static void main(String[] args) {
        // float a=7/4*9/2;// Since the 7/4 will give integer value and then 1*9/2 will also give integer value because the division of two integer is integer....
        // To find out the real answer we have to write the sam expression in such a manner ....
         float a=7/4f*9/2f; // Here the f is used for conversion to floating point number.......
        System.out.println(a);
    }
}
