public class CWH_lect_69_Multithreading {
    // It is being used to achieve multiTasking....
    // With in a process multi Tasking....Then we use Threading
    // Threading is being used for the program to execute or run it fast by concrete operations...
    // Way for implementing thread is :
    // 1)By extending Thread class...
    //2)By implementing Renuable interface... 
    public static void main(String[] args) {
        
    }
}
